import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/Header";
import Barralateral from "@/components/Barralateral.tsx";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <ClerkProvider>
        <body>
          <Header />
          <div className="flex min-h-screen">
            <Barralateral />
            <div className="flex-1 p-4 bg-gray-100 overflow-y-auto scrollbar-hide">
              {children}
            </div>
            <Toaster position="top-center"/>
          </div>
        </body>
      </ClerkProvider>
    </html>
  );
}
